### PR TITLE
Added @Ignore attribute to randomly failing test

### PR DESCRIPTION
**Pull request by samuelmale**
Issue : https://issues.openmrs.org/browse/EA-141

### CODE REVIEW

**Comment by dkayiwa** [comment]
@samuelmale why TRUNK-5342 in this commit message?

**Comment by samuelmale** [comment]
Just removed it @dkayiwa

**Comment by samuelmale** [comment]
> You should have the ignored text ticket in your commit message

Still trying to understand which text you mean exactly @dkayiwa

**Comment by samuelmale** [comment]
I think I have modified the commit message according @dkayiwa

**Comment by samuelmale** [comment]
Hope we good man

**Comment by dkayiwa** [comment]
@samuelmale just adding the ticket number to your original commit message would have been enough

**Comment by samuelmale** [comment]
@dkayiwa  just changed it

**Comment by dkayiwa** [comment]
Thanks @samuelmale 👍

**Pull request merged**
