### PR TITLE
EA-210 Add encounter types for cancelling ADT request and for bed ass…

### PR DESCRIPTION
**Pull request by chibongho**
…ignment

See: https://openmrs.atlassian.net/browse/EA-210

### CODE REVIEW

**Review by mseaton — APPROVED** [review]
Seems ok

**Review by mogoodrich — APPROVED** [review]
This makes sense, @chibongho , LGTM... (though see my note on the other PR, we will just want to set this to the existing the Cancel Admission encounter type)

**Comment by chibongho** [comment]
Should I do `emr.cancelADTRequestEncounterType` here or `emr.cancelAdmissionEncounterType`?

**Comment by mogoodrich** [comment]
> Should I do `emr.cancelADTRequestEncounterType` here or `emr.cancelAdmissionEncounterType`?

Sorry @chibongho  just seeing this now, but, yeah, I'd go with the second one (like you did).

**Pull request merged**
