### PR TITLE
EA-121 | Conditions List implementation

### PR DESCRIPTION
**Pull request by sidtharthanan**
* Added web endpoint for conditions and condition history.
* Changed the status to ACTIVE, INACTIVE and HISTORY_OF.

### CODE REVIEW

**Comment by sidtharthanan** [comment]
openmrs Issue: https://issues.openmrs.org/browse/EA-121

**Comment by dkayiwa** [comment]
@sidtharthanan did you take a look at the travis failure?

**Comment by sidtharthanan** [comment]
@dkayiwa We have fixed the build failure.
Could you have a look at it now?

**Comment by sidtharthanan** [comment]
@dkayiwa Thanks for merging.

Could you back port it to 1.20 also?

**Comment by dkayiwa** [comment]
What is 1.120? 😊

**Comment by sidtharthanan** [comment]
I mean [emrapi version 1.20](https://github.com/openmrs/openmrs-module-emrapi/tree/1.20)

**Comment by dkayiwa** [comment]
You can create a branch off the 1.20 tag and put those changes in if you do not want to use the latest version.

**Comment by sidtharthanan** [comment]
Okay, Thanks.

**Pull request merged**
