### PR TITLE
Removed the obsDateTime to default to the encounterDateTime for new Obs and instead use the current date.

### PR DESCRIPTION
**Pull request by mihirk**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@mihirk do you mind pointing me to the pull request for this? :)

**Comment by dkayiwa** [comment]
@mihirk are you still available to squash these commits into one? And also create a ticket for this? Finally look into merge conflicts.

**Comment by mihirk** [comment]
Hey Daniel this is pretty old, I don't even remember it now, let me take a look at it and get back to you.

**Comment by dkayiwa** [comment]
@mihirk yes it is pretty old. I almost closed it. But decided to first ask, just in case you are still interested in it. :)

**Comment by dkayiwa** [comment]
@mihirk ok, am closing it for now. :)

**Pull request closed without merging**
