### PR TITLE
EA-150: Fixed error while saving condition

### PR DESCRIPTION
**Pull request by haripriya999**
#  EA-150 : Save Condition error of condition list fixed

## Description of what I changed
 Fixed the bug which prevented the condition from being saved.

## Issue I worked on

see https://issues.openmrs.org/browse/EA-150

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
I get an error on trying to save a condition. And here is the stack trace: https://pastebin.com/Q2axFTgi

**Comment by haripriya999** [comment]
What are the steps to generate this error?

**Comment by dkayiwa** [comment]
The exact steps you reported on the ticket

**Comment by haripriya999** [comment]
The changes made in this PR is working for me. I'm not able to generate the error you encountered. May be the error is value specific, could you please provide me with the inputs you gave.

**Comment by dkayiwa** [comment]
Do you have a standalone zip of the openmrs reference application version 2.9.0?

**Comment by dkayiwa** [comment]
Can you create a new SDK server and see the error that am reporting?

**Comment by haripriya999** [comment]
I just did that and its working for me without generating any error log.

**Comment by haripriya999** [comment]
I suspect this error to be value specific. Can you tell me the name of the condition that you added which generated this error?

**Comment by dkayiwa** [comment]
When creating a new sdk server, which options did you choose?

**Comment by haripriya999** [comment]
Distribution Platform , RA 2.9.0

**Pull request merged**
