### PR TITLE
EA-141: UnIgnored the test_getVisitsAndHasVisitDuring Test because it…

### PR DESCRIPTION
**Pull request by Ruhanga**
Randomly failing test passes successfully without any significant change to its code

link to ticket

https://issues.openmrs.org/browse/EA-141

### CODE REVIEW

**Comment by dkayiwa** [comment]
You have just unignored without fixing the randomly failing test.

**Comment by Ruhanga** [comment]
Yes @dkayiwa , this is because the error was not reproducible after multiple compilations.

**Comment by dkayiwa** [comment]
@Ruhanga how many times did you compile?

**Comment by Ruhanga** [comment]
I clean installed five consecutive times plus one more time a few hours, ago all terminating into a build success.

**Comment by dkayiwa** [comment]
@Ruhanga can you do it again like 10 more times?

**Pull request closed without merging**
