### PR TITLE
Ea104

### PR DESCRIPTION
**Pull request by sravanthi17**
Please find the openmrs issue link @https://issues.openmrs.org/browse/EA-104

### CODE REVIEW

**Comment by sravanthi17** [comment]
Will raise a new request. Sorry for the inconvenience

**Comment by mogoodrich** [comment]
For what it's worth, looks like the EMR-API build is still broken, even after this revert.  May have something to do with the version of Java we are using to compile?

**Comment by dkayiwa** [comment]
@mogoodrich does it also fail locally? I suspect it could be a side effect of @maurya's bumping the platform version to 2.0

**Comment by mogoodrich** [comment]
It fails on PIH bamboo as well.  Will test locallly now.

Where did we upgrade the platform version?  In the reference app distro?  I think this would definitely cause problems, especially if 2.0 requires Java 8?  We will have to figure out a strategy for this.

**Comment by dkayiwa** [comment]
Yes in the refapp distro. Let me revert it for now to see if it fixes.

**Comment by mogoodrich** [comment]
I'll post to talk about it, will @ you...

**Pull request closed without merging**
