### PR TITLE
EA-131|EmrConceptSearchController should allow search by concept refe…

### PR DESCRIPTION
**Pull request by ShruthiPitta**
…rence term code

### CODE REVIEW

**Comment by dkayiwa** [comment]
@ShruthiPitta did you get a chance to look at our pull request process here? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
@ShruthiPitta did you get a chance to look at under the JIRA workflow section on that tips page? 😊

**Comment by ShruthiPitta** [comment]
Yes. I have claimed the issue on JIRA now. Will also create a new PR following the steps there. Sorry for not following the convention. @dkayiwa

**Comment by ShruthiPitta** [comment]
Closing the PR. Will create a new one.

**Pull request closed without merging**
