### PR TITLE
EA-109 | Fix for duplication of disposition obs group on edit and add…

### PR DESCRIPTION
**Pull request by preethi29**
… profile for running tests against openmrs2.0

### CODE REVIEW

**Comment by dkayiwa** [comment]
@preethi29 did you notice the travis failure?

**Comment by preethi29** [comment]
@dkayiwa It passes in my local. Is there a way to view the surefire-reports?

**Comment by dkayiwa** [comment]
@preethi29 did you already see this? https://travis-ci.org/openmrs/openmrs-module-emrapi/builds/173206694

**Comment by preethi29** [comment]
Yeah I have taken a look at it. It just says error in tests. I would need to see the surefire-reports to see the detail of the error.

**Comment by preethi29** [comment]
@dkayiwa Build passed. It was failing to case sensitive in dataset filename. Now its green

**Comment by dkayiwa** [comment]
@preethi29 oh great! :)

**Comment by preethi29** [comment]
@dkayiwa Thanks :)

**Comment by dkayiwa** [comment]
@preethi29 does this compile successfully for you on Java 7?

**Comment by preethi29** [comment]
@dkayiwa I have added MRS2.0 profile to run tests against openmrs 2 which essentially uses BaseModuleContextSensitiveTest that is compiled in java 8. Thats why when running tests in jdk 7, it throws java.lang.UnsupportedClassVersionError.

 Have you faced this kind of problem before since there are many modules which run tests against mrs 1.x and 2.x? If so, how was it solved?

**Comment by dkayiwa** [comment]
@preethi29 as you can see here https://github.com/openmrs/openmrs-module-reporting/blob/master/pom.xml#L322 we do not make that profile active by default. We let whoever is compiling to activate that profile if they are using java 8

**Pull request merged**
