### PR TITLE
EA-162: Add support for FHIR condition resource

### PR DESCRIPTION
**Pull request by corneliouzbett**
Issue worked on:
https://issues.openmrs.org/browse/EA-162

This PR adds support for FHIR conditions by:
- Adding mapping from EMR condition to FHIR condition (R4 & R3)
- Adds new Dao layer to support FHIR search operations

**NOTE**
 In case someone wants to see this in action. I already uploaded `1.31.0-SNAPSHOT`of the EMR API module to the [openmrs-spa instance](https://openmrs-spa.org/openmrs).

### CODE REVIEW

**Comment by corneliouzbett** [comment]
@dkayiwa How can I request a reviewer? Currently, this repo doesn't allow me to do so.

**Comment by corneliouzbett** [comment]
I will do a follow-up PR to add Dao and search Integration tests

**Comment by dkayiwa** [comment]
@corneliouzbett i have made the ticket ready for work. So you can claim it.

**Comment by gracepotma** [comment]
@ibacher can this be merged and https://issues.openmrs.org/browse/FM2-310 closed?

**Review by ibacher — APPROVED** [review]

**Pull request merged**
