### PR TITLE
EA-164: Add support to create, and update FHIR condition

### PR DESCRIPTION
**Pull request by corneliouzbett**
**Issue worked on:**
https://issues.openmrs.org/browse/EA-164

**Changes**
- Adds support to create and update conditions
- Renamed the package

### CODE REVIEW

**Comment by corneliouzbett** [comment]
Kindly review @ibacher @dkayiwa

**Comment by dkayiwa** [comment]
Can you add the ticket id to the commit message?

**Comment by corneliouzbett** [comment]
> Can you add the ticket id to the commit message?

Done ✅

**Comment by dkayiwa** [comment]
Do you also mind explaining how these changes support creating and updating FHIR conditions for openmrs platform version 2.0.5 - 2.1.4?

**Comment by corneliouzbett** [comment]
> Do you also mind explaining how these changes support creating and updating FHIR conditions for openmrs platform version 2.0.5 - 2.1.4?

So the previous PR #192  and #195 introduces a `fhir-condition` sub-module which has the functionality/logic to `create`, `update`, and perform `search` operations on conditions. This piece of logic(in a jar file) is loaded conditionally;
 - If the fhir2 module is present 
- If the openmrs-platform version is 2.0.5 - 2.1.4
```java
<conditionalResource>
    <path>/lib/emrapi-fhir-condition-${project.parent.version}.jar</path>
        <loadIfModulesPresent>
            <openmrsModule>
                 <moduleId>org.openmrs.module.fhir2</moduleId>
                 <version>1.*</version>
             </openmrsModule>
         </loadIfModulesPresent>
      <openmrsVersion>2.0.5 - 2.1.*</openmrsVersion>
</conditionalResource>
```
This #195 specifically, fixes create and update. Well it does more,  some other quick refactoring
 - Upgrading fhir2 from version 1.0.0 - adds some refactoring to condition resource - essential for search, create & update
 - Renaming of the package
 - Removal of `HISTORY_OF` condition clinical status - Not a valid FHIR spec

**Comment by corneliouzbett** [comment]
@dkayiwa PTAL 👆🏾

**Pull request merged**
