### PR TITLE
MAP-19: Setting a UUID to the extra PIT metadata set.

### PR DESCRIPTION
**Pull request by mks-d**

### CODE REVIEW

**Comment by mogoodrich** [comment]
Actually, if it's easy enough (I think it is?) can you add code to fetch the metadata set by it's code and then update the uuid if necessary, so that implementations won't have to write their own migrations? @mks-d

**Comment by mks-d** [comment]
@mogoodrich where do you see this to happen?

**Comment by mogoodrich** [comment]
I would think just within the createExtraPatientIdTypesSetIfMissing method, ie if extraPatientIdTypesMapping != null then update the uuid, though I guess this would a bit dangerous.  Though the flip side is that all existing implementatoins would have a uuid that doesn't match the constant.

**Comment by mks-d** [comment]
@mogoodrich FYI @Ruhanga will do the follow-up commit as per your suggestion.

**Pull request merged**
